name: .NET


on:
  push:
    tags:
      - 'v*'

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/Eco.Echolon.ApiClient/bin/Release
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set 
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet pack --configuration Release --include-symbols /p:Version=${{ env.RELEASE_VERSION }} --no-restore
    - name: Publish NuGet
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }}
